// Generated by gse_generate.py — DO NOT EDIT
// GSE-One version: 0.81.3
// Reproduces hooks/hooks.claude.json guardrails as a native opencode plugin.
import type { Plugin } from "@opencode-ai/plugin"
import { $ } from "bun"

export const GseGuardrails: Plugin = async () => {
  return {
    "tool.execute.before": async (input: any, output: any) => {
      if (input?.tool !== "bash") return
      const cmd = String(output?.args?.command ?? "")

      // Project-local config toggles (.gse/config.yaml -> hooks section)
      let cfg = ""
      try { cfg = await Bun.file(".gse/config.yaml").text() } catch { /* no config */ }

      if (/\bgit\s[^|;&]*\bpush\b[^|;&]*(\s-f\b|--force\b)/.test(cmd)) {
        if (!/^\s*block_force_push:\s*false/m.test(cfg)) {
          throw new Error(
            "EMERGENCY GUARDRAIL: Force push detected (-f / --force / --force-with-lease). This can cause permanent data loss. Aborting."
          )
        }
      }

      if (/(?:^|[;&|]\s*)git\s+(-C\s+\S+\s+)?commit\b/.test(cmd)) {
        const off = /^\s*protect_main:\s*false/m.test(cfg) || /^\s*strategy:\s*none/m.test(cfg)
        if (!off) {
          const branch = (await $`git branch --show-current`.text()).trim()
          if (branch === "main") {
            // Repository-initialization exception: no HEAD yet (foundational commit)
            const head = await $`git rev-parse --verify HEAD`.nothrow().quiet()
            if (head.exitCode === 0) {
              throw new Error(
                "GUARDRAIL: Direct commit to main detected. Use a feature branch. (Sanctioned exceptions: hooks.protect_main: false or git.strategy: none in .gse/config.yaml; repository-initialization commit.)"
              )
            }
          }
        }
      }
    },

    "tool.execute.after": async (input: any, _output: any) => {
      // Bash / git push — open review findings warning
      if (input?.tool === "bash") {
        const cmd = String(input?.args?.command ?? "")
        if (/\bgit\s[^|;&]*\bpush\b/.test(cmd)) {
          try {
            let cfgAfter = ""
            try { cfgAfter = await Bun.file(".gse/config.yaml").text() } catch { /* no config */ }
            if (/^\s*review_findings_on_push:\s*false/m.test(cfgAfter)) return
            const status = await Bun.file(".gse/status.yaml").text()
            const m = status.match(/review_findings_open:\s*(\d+)/)
            const open = m ? parseInt(m[1], 10) : 0
            if (open > 0) {
              console.warn(`WARNING: ${open} open review findings`)
            }
          } catch {
            // .gse/status.yaml absent — nothing to report
          }
        }
        return
      }

      // Dashboard sync — fire on edit/write/multiedit (ENH-02).
      // Mirrors the PostToolUse hooks in hooks.claude.json / hooks.cursor.json,
      // including the double-defense error marker on subprocess failure.
      const toolName = String(input?.tool ?? "").toLowerCase()
      if (["edit", "write", "multiedit"].includes(toolName)) {
        try {
          const home = process.env.HOME ?? ""
          const registryPath = `${home}/.gse-one`
          const registryFile = Bun.file(registryPath)
          if (!(await registryFile.exists())) return
          const pluginPath = (await registryFile.text()).trim()
          if (!pluginPath) return
          const tool = `${pluginPath}/tools/dashboard.py`
          if (!(await Bun.file(tool).exists())) return
          const result = await $`python3 ${tool} --if-stale`.nothrow().quiet()
          if (result.exitCode !== 0) {
            // Double-defense: dashboard.py crashed before its own try/except ran
            const now = new Date().toISOString().replace(/\.\d+Z$/, "Z")
            const stderr = result.stderr?.toString() ?? "(no stderr)"
            const msg = JSON.stringify(`dashboard.py exited with code ${result.exitCode}`)
            const indented = stderr.split("\n").map((l: string) => `  ${l}`).join("\n")
            const content =
              `timestamp: "${now}"\n` +
              `message: ${msg}\n` +
              `traceback: |\n${indented}\n`
            try {
              await Bun.write(".gse/.dashboard-error.yaml", content)
            } catch { /* best-effort */ }
          }
        } catch {
          // Hook wrapper must never block the edit
        }
      }
    },
  }
}

export default GseGuardrails
